#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/config/config.php';

define("CONFIG",$config);


use Symfony\Component\Console\Application;
use Dcr\Console\Command\GetCommand;
use Dcr\Console\Command\PublishCommand;

$application = new Application();
$application->add(new GetCommand);
$application->add(new PublishCommand);
$application->run();
